feat: hcsr04 sensor implementation
fossasia/pslab-firmware pull request #118
Opened 2021-10-21 12:12 UTC by CloudyPadmal

TODO:
- [x] Create a new `SENSORS` block in states
- [x] Move and use `Interval` functions from #122 
- [X] Offload `disable_IC` to logic analyzer; may be?

2022-03-21 11:28 UTC, bessman requested changes
In addition to the comments below, I question the necessity of implementing this in firmware at all. As far as I can tell, this sensor could be implemented in software by combining the PWM generator to generate the trigger pulse with the logic analyzer to receive the echo pulse.

2022-03-21 11:28 UTC, bessman commented on pslab-core.X/instruments/sensors.h
> +        ________________________|--------...----|__
If we are OK with unicode in comments:
```suggestion
        _|‾‾‾‾‾|_______________________________________________
          <10us>
        __________|‾|_|‾|_|‾|_|‾|_|‾|_|‾|_|‾|_|‾|______________
                 <--- Burst --->
     >  Echo Pin (LA1)
        ___________________________________________|‾‾‾...‾‾‾|_
```

2022-03-22 12:58 UTC, CloudyPadmal commented on pslab-core.X/instruments/sensors.c
> +    while ((!_IC1IF) && (IC2TMR < timeout));
I'll add more stuff to the documentation. May be with some sample values for timeout..

Note that, we are using cascaded capture timers. So it's 32 bits instead of 16 bits making it way more than 1 ms.

2022-03-22 12:59 UTC, CloudyPadmal commented on pslab-core.X/instruments/sensors.h
> +        ________________________|--------...----|__
Looks good!

2022-03-22 13:49 UTC, bessman commented on pslab-core.X/instruments/sensors.c
> +    while ((!_IC1IF) && (IC2TMR < timeout));
Even if the timer is 32-bit, the `timeout` variable is a uint16_t.

2022-03-22 13:57 UTC, CloudyPadmal commented on pslab-core.X/instruments/sensors.c
> +    while ((!_IC1IF) && (IC2TMR < timeout));
Doesn't matter because when IC1 and IC2 are in cascade, IC1TMR fills up fully when IC2TMR increment by one bit. And we are only checking IC2TMR

2022-03-22 15:12 UTC, CloudyPadmal commented on pslab-core.X/instruments/sensors.h
> +        __________________________|-------- ... ----|__
Had to revert the characters as it is not displayed properly in MPLab IDE

2022-03-22 19:29 UTC, bessman commented on pslab-core.X/instruments/sensors.c
> +    while ((!_IC1IF) && (IC2TMR < timeout));
OK, I see. So the value of `timeout` is roughly the actual timeout in milliseconds (`timeout * 1.024 ms` to be exact). That's pretty clever. But not very obvious, a comment explaining it would be useful.

2022-03-22 19:56 UTC, bessman commented on pslab-core.X/instruments/sensors.h
> +     *    For sanity checking
This could be clearer. What should be checked, exactly? The comment in the .c file says

> Fetch the timer value from IC2 module to measure ToF from python side

but I don't see how just a single timer value can be used for that.

2022-03-23 11:55 UTC, bessman commented
Here is a software implementation in Python:
```python
import time

from pslab.instrument.logic_analyzer import LogicAnalyzer
from pslab.instrument.waveform_generator import PWMGenerator

class HCSR04Soft(LogicAnalyzer, PWMGenerator):
    def __init__(self, device):
        self._device = device
        self._measure_period = 60e-3
        self._trigger_pulse_length = 10e-6

    def estimate_distance(
            self,
            trig="SQ1",
            echo="LA1",
            average=10,
            speed_of_sound=340
        ):
        self.capture(channels=echo, events=2*average, block=False)
        self.generate(
            channels=trig,
            frequency=self._measure_period ** -1,
            duty_cycles=self._trigger_channel / self._measure_period
        )
        time.sleep(self._measure_period * average)
        self.set_state(**{trig.lower(): 0})
        (t,) = self.fetch_data()
        high_times = t[::2] - t[1::2]
        return speed_of_sound * high_times.mean() / 2
```
Haven't tested it since I don't have the sensor, but it should work. This implementation has a number of benefits over the firmware:
- The TRIG and ECHO pins are user configurable.
- The speed of sound can be changed, for example based on measurements from a temperature and humidity sensor.
- The measurement can be easily repeated with no overhead via the `average` argument. Rerunning the firmware implementation the same number of times will be slower.
- Much less code to maintain.

2022-03-23 16:00 UTC, CloudyPadmal commented
@bessman sorry I didn't see the question of implementing this in Python earlier. I think that's a good idea and I just checked the code snippet you shared and it works! It's a neat trick to use the logic analyser to capture multiple samples to average the result. I like to go ahead with the Python path. Let me close this PR and link it to python-repo as an issue.

2022-03-23 16:00 UTC, closed without merging